warn if self-closing tag is used
formatjs/formatjs-old pull request #166
Opened 2019-08-28 01:14 UTC by tranvansang

The edit is not well tested. I edited it directly in github

2019-08-28 01:26 UTC, longlho requested changes

2019-08-28 01:26 UTC, longlho commented on packages/intl-messageformat/src/formatters.ts
> +        console.warn(`${tagName} is a self-closing tag and can not be used, please use another tag name.`)
u should just `throw` a `FormatError` cause it'll produce invalid output (swallow children) which is even harder to debug

2019-08-28 01:40 UTC, longlho requested changes

2019-08-28 01:40 UTC, longlho commented on packages/intl-messageformat/src/formatters.ts
> +      if (process.env.NODE_ENV !== 'production' && [
I think u can drop `process.env.NODE_ENV` check as well

2019-08-28 01:40 UTC, longlho commented on packages/intl-messageformat/src/formatters.ts
> +      ].includes(tagName))
`~[].indexOf()` bc IE11 (& we don't package w/ any polyfill due to weight)

2019-08-28 01:40 UTC, longlho commented on packages/intl-messageformat/src/formatters.ts
> +        throw new Error(`${tagName} is a self-closing tag and can not be used, please use another tag name.`)
`throw new FormatError`

2019-08-28 03:24 UTC, longlho approved these changes

2019-08-28 03:24 UTC, longlho commented
Thanks a lot for your contributions!

2019-08-28 03:25 UTC, merged

2019-08-29 00:43 UTC, klimashkin commented
Is there a `why` ticket for these changes?

2019-08-29 00:50 UTC, longlho commented
context: 
https://github.com/formatjs/formatjs/issues/152
https://github.com/formatjs/formatjs/issues/148

This is to prevent footguns where you can specify `<br>blah</br>` and have `blah` be swallowed by `DOMParser`.

We've added caveats here: https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat#caveats