chore: consolidate config files
formatjs/formatjs-old pull request #50
Opened 2019-06-01 03:47 UTC by longlho

2019-06-01 05:37 UTC, redonkulus requested changes
I think the downside to rollup and mocha consolidation is that you basically run the build and test of all packages regardless of whether the packages changed. This could lead to unnecessary patch publishes by lerna. 

For rollup and mocha, you can just update the run script of each package to point to the shared mocha.opts and rollup config at the monorepo root.

I like leveraging lerna to only build what changed and its dependencies instead of all the things.

2019-06-01 05:37 UTC, redonkulus commented on package.json
> +    "build:packages": "npm run clean && lerna run clean && lerna run build --since --stream",
I think lerna clean asks for confirmation to delete. Add `—yes` to avoid the prompt.

2019-06-01 05:37 UTC, redonkulus commented on mocha.opts
> +packages/**/tests/index.ts
We don’t really want to test every package every build. We should just leverage lerna and only run for what changed.

2019-06-01 05:37 UTC, redonkulus commented on package.json
> +    "test": "lerna run lint --since --stream && npm run mocha && lerna run test --since --stream",
It runs mocha and lerna run test?

2019-06-01 05:37 UTC, redonkulus commented on packages/intl-format-cache/package.json
> +  "devDependencies": {
Remove

2019-06-01 05:37 UTC, redonkulus commented on packages/intl-format-cache/.gitignore
> +src/*.js
Ignore source?

2019-06-02 02:28 UTC, longlho commented on packages/intl-format-cache/package.json
> +  "devDependencies": {
This is actually needed so that lerna runs these packages before `intl-format-cache`

2019-06-02 02:52 UTC, redonkulus approved these changes

2019-06-02 03:09 UTC, merged